FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY ["Auth-api.csproj", "./"]

RUN dotnet restore "./Auth-api.csproj"
COPY . .

WORKDIR "/src/."

RUN dotnet build "Auth-api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Auth-api.csproj" -c Release -o /app/publish

FROM base AS final

WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Auth-api.dll"]